### PR TITLE
Add check for curl.

### LINKED ISSUE #3: use curl if available
determine whether curl is available and use that, fall back to wget if not, otherwise error

### PR DESCRIPTION
**Pull request by ghost**
If curl exists, use it. Otherwise try wget.
If neither exist, exit saying so.

Fixes #3.

### CODE REVIEW

**Comment by goshhhy** [comment]
this pr has bashisms, can't accept as is

needs to be able to run on systems with dash as /bin/sh

**Comment by ghost** [comment]
Fixed, and I tested this under dash this time, too. (And sh, and bash)

**Comment by goshhhy** [comment]
wget -d0- isn't accepted by my wget

change it to -qO- and i'll merge

**Comment by ghost** [comment]
I shouldn't work on PRs until _after_ I finish my coffee...

This is fixed now!

**Pull request merged**
